### PR TITLE
Update omgwtfnzbs.js

### PR DESCRIPTION
**Pull request by pbourdon71**
This is to address the URL change for omgwtfnzb

### CODE REVIEW

**Comment by treyturner** [comment]
This appears to be a duplicate of https://github.com/gboudreau/sabconnectplusplus/pull/149

**Comment by gboudreau** [comment]
Indeed, dupe.

**Comment by pbourdon71** [comment]
There seems to be an error -

Package is invalid. Details: 'Could not load background script
'third_party/fancy-settings/lib/store.js'.'.
RELOAD
CLOSE
<https://chrome.google.com/webstore/category/extensions>

**Comment by AnthraxLeprosyPi** [comment]
Same here... cant downoad from webstore

regards
Anthrax

**Comment by gboudreau** [comment]
Fixed in 0.6.22; just uploaded.

**Comment by pbourdon71** [comment]
Thank you

**Pull request closed without merging**
